#!/bin/bash
#
# Useful for visually inspecting the output SQL to verify it is doing what it should
#

source ./start-fresh.sh >/dev/null
echo
echo ==========================================================
echo

#
# Compare the indexes between two schemas in the same database
#

./populate-db.sh db1 '
    CREATE SCHEMA s1;
    CREATE TABLE s1."Table1" (
      id integer PRIMARY KEY,
      name varchar(32),
      url varchar(200)
    );
    CREATE INDEX "Table1NameIx" ON s1."Table1"(name);

    CREATE SCHEMA s2;
    CREATE TABLE s2."Table1" (
      id integer PRIMARY KEY, 
      name varchar(32),
      url varchar(200)
    );
    CREATE INDEX Table1NameIx ON s2."Table1"(name); -- index name stored as lower case
    CREATE INDEX ON s2."Table1"(url);
'

echo
echo "# Compare the indexes between two schemas in the same database"
echo "# Expect SQL (pseudocode):"
echo "#   Drop s2.table1nameix"
echo "#   Add s2.Table1NameIx"
echo "#   Drop lower-case index on s2.Table1.url"
echo

../pgdiff -U "u1" -W "asdf" -H "localhost" -D "db1" -S "s1" -O "sslmode=disable" \
          -u "u1" -w "asdf" -h "localhost" -d "db1" -s "s2" -o "sslmode=disable" \
          INDEX | grep -v '^-- '
echo
echo ==========================================================
echo

#
# Compare the indexes in all schemas between two databases
#
./populate-db.sh db2 '
    CREATE SCHEMA s1;
    CREATE TABLE s1."Table1" (
      id integer PRIMARY KEY,
      name varchar(32),
      url varchar(200)
    );
    CREATE INDEX "Table1NameIx" ON s1."Table1"(name);
    CREATE INDEX ON s1."Table1"(url);

    CREATE SCHEMA s2;
    CREATE TABLE s2."Table1" (
      id integer PRIMARY KEY, 
      name varchar(32),
      url varchar(200)
    );
    CREATE INDEX Table1NameIx ON s2."Table1"(name); -- index name stored as lower case 
'

echo
echo "# Compare the indexes in all schemas between two databases"
echo "# Expect SQL (pseudocode):"
echo "#   Drop index on db2 s1.table1.url"
echo "#   Add index on db2 s2.table1.url"
echo

../pgdiff -U "u1" -W "asdf" -H "localhost" -D "db1" -S "*" -O "sslmode=disable" \
          -u "u1" -w "asdf" -h "localhost" -d "db2" -s "*" -o "sslmode=disable" \
          INDEX | grep -v '^-- '
echo
echo
