#!/bin/bash
#
# Useful for visually inspecting the output SQL to verify it is doing what it should
#

source ./start-fresh.sh >/dev/null 

echo
echo ==============================================================

echo
echo "# Compare the tables in two schemas in the same database"
echo "# Expect SQL:"
echo "#   Add table9 to schema s2"
echo "#   Drop table11 from schema s2"

#
# Compare the tables in two schemas in the same database
#
#psql -U u1 -h localhost -d db1 <<'EOS'
./populate-db.sh db1 "
    CREATE SCHEMA s1;
    CREATE TABLE s1.table9 (id integer); -- to be added to s2
    CREATE TABLE s1.table10 (id integer);
    
    CREATE SCHEMA s2;
    CREATE TABLE s2.table10 (id integer);
    CREATE TABLE s2.table11 (id integer); -- will be dropped from s2
"

echo
echo "SQL to run:"
../pgdiff -U "u1" -W "asdf" -H "localhost" -D "db1" -S "s1" -O "sslmode=disable" \
          -u "u1" -w "asdf" -h "localhost" -d "db1" -s "s2" -o "sslmode=disable" \
          TABLE | grep -v '^-- '

echo
echo ==============================================================

echo
echo "# Compare the tables in all schemas in two databases"
echo "# Expect:"
echo "#   Add s1.table10 to db2"
echo "#   Drop s2.table12 from db2"


./populate-db.sh db2 "
    CREATE SCHEMA s1;
    CREATE TABLE s1.table9 (id integer);
    -- table10 will be added in db2

    CREATE SCHEMA s2;
    CREATE TABLE s2.table10 (id integer); 
    CREATE TABLE s2.table11 (id integer);
    CREATE TABLE s2.table12 (id integer); -- will be dropped (not in db1)

    CREATE SCHEMA s3;
"

echo
echo "SQL to run:"
../pgdiff -U "u1" -W "asdf" -H "localhost" -D "db1" -S "*" -O "sslmode=disable" \
          -u "u1" -w "asdf" -h "localhost" -d "db2" -s "*" -o "sslmode=disable" \
          TABLE | grep -v '^-- '
echo
